config/routes.rb
Aqqaluk::Application.routes.draw do
  root :to => 'pages#home'

  get '/home',           to: 'pages#home'
  get '/home_v2',        to: 'pages#home_v2'
  get '/about-us',       to: 'pages#about_us',       as: :about_us
  get '/news',           to: 'pages#news'
  get '/founder',        to: 'pages#founder'
  get '/board-members',  to: 'pages#board_members',  as: :board_members
  get '/staff',          to: 'pages#staff'
  get '/education',      to: 'pages#education'
  get '/students_v1',    to: 'pages#students_v1'
  get '/savaktuq',       to: 'pages#savaktuq'
  get '/faq',            to: 'pages#faq'
  get '/blog',           to: 'pages#blog'
  get '/language',       to: 'pages#language'
  get '/language_v1',    to: 'pages#language_v1'
  get '/camp',           to: 'pages#camp'
  get '/support',        to: 'pages#support'
  get '/golf-challenge', to: 'pages#golf_challenge', as: :golf_challenge
  get '/memorial-fund',  to: 'pages#memorial_fund',  as: :memorial_fund

  comfy_route :cms_admin, :path => '/admin'
  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Mobvious::Rails::Controller

  before_filter :prepare_for_mobile


  private

  def prepare_for_mobile
    if request.env['mobvious.device_type'] == :mobile
      prepend_view_path "app/views/mobile"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def home_v2
  end

  def about_us
  end

  def news
  end

  def founder
  end

  def board_members
  end

  def staff
  end

  def education
  end

  def students_v1
  end

  def savaktuq
  end

  def faq
  end

  def blog
  end

  def language
  end

  def language_v1
  end

  def camp
  end

  def support
  end

  def golf_challenge
  end

  def memorial_fund
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Mobvious::Rails::Helper

  def head
    render :partial => 'layouts/head'
  end

  def scripts
    render :partial => 'layouts/scripts'
  end

  def browsehappy
    render :partial => 'layouts/browsehappy'
  end

  def title(page_title)
    content_for(:title) { page_title }
  end

  def nav_switch(title)
    if device_type == :mobile
      nav_at(title, {in: :mobile})
    else
      nav_at(title)
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def default_markdown_source
    '### add some content here'
  end
end

app/views/layouts/_browsehappy.html.haml
/[if lt IE 8]
  %p.browsehappy
    You are using an <strong>outdated</strong> browser. Please
    %a{:href => "http://browsehappy.com/"} upgrade your browser
    to improve your experience.

app/views/layouts/_footer.html.haml
%footer{:role => "contentinfo"}
  .container
    .footer-left
      .address
        .vcard
          %p.fn.org
            Aqqaluk Trust
          .adr
            %p.street-address P.O. Box 509
            %p
              %span.locality> Kotzebue
              ,
              %span.region Alaska
              %span.postal-code 99752
      .social-media
        = render 'shared/social_media'
    .phone-number
      %p
        Toll Free --
        %a{:href => 'callto://1-866-442-1607', :title => 'Toll Free Number', :class => 'callto'} 866-442-1607
        %a{:href => 'tel://1-866-442-1607', :title => 'Toll Free Number', :class => 'tel'} 866-442-1607
      %p
        Phone --
        %a{:href => 'callto://907-442-1607', :title => 'Main Number', :class => 'callto'} 907-442-1607
        %a{:href => 'tel://907-442-1607', :title => 'Main Number', :class => 'tel'} 907-442-1607
      %p
        Fax -- 907-442-2289
      %p
        :javascript
          <!--
          var elumbbh = ['k','k','a','m','.','m','=','r','.','i','o','f','o','s','a','.','i','s','t','s','t','q','c','>',' ','@','t','u','"','u','t','l','s','k','c','>','c','a','l','"','q','u','t','l','a','a','u','m','k','h','<',' ','q','=','t','l','a','m','q','r','q','q','t','u','l','/','e','s','r','.','l','t','a','a','@','q','a','q','o','a','u','s','a','u','"','a','r','<','t','"','r','e','u',':','l','a'];var mjxnfvp = [82,22,10,91,88,56,53,4,42,58,44,6,90,27,50,69,11,51,41,52,70,77,43,61,2,75,83,67,8,72,87,49,73,68,89,95,48,16,59,60,18,21,28,80,76,19,26,9,36,3,92,47,31,7,37,20,33,45,63,25,64,32,24,39,34,93,5,40,71,23,12,74,30,79,29,17,1,78,14,62,35,86,65,81,46,94,38,0,13,54,84,55,85,15,66,57];var olebmmb= new Array();for(var i=0;i<mjxnfvp.length;i++){olebmmb[mjxnfvp[i]] = elumbbh[i]; }for(var i=0;i<olebmmb.length;i++){document.write(olebmmb[i]);}
          // -->
        %noscript Please enable Javascript to see the email address
    %p.copyright &copy; Aqqaluk Trust 2014

app/views/layouts/_head.html.haml
%head
  %meta{:charset => "utf-8"}
  %link{:rel => "dns-prefetch", :href => "//use.typekit.net"}
  %link{:rel => "dns-prefetch", :href => "//fonts.googleapis.com"}
  /[if IE] %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}

  %title= content_for?(:title) ? ("Aqqaluk Trust - " + yield(:title)) : "Aqqaluk Trust"

  %meta{:name => "description", :content => "Aqqaluk Trust"}
  %meta{:name => "viewport", :content => "width=device-width"}
  -# to match layout to device width and set zoom level to 1:1
  -# %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}

  %meta{:property => "og:title",       :content => "Aqqaluk Trust"}
  %meta{:property => "og:description", :content => "Empowering the Iñupiat through language, culture and education."}
  %meta{:property => "og:image",       :content => "http://cdn0.aqqaluktrust.com/assets/touch/apple-touch-icon-d3105c0e2ad7c23feea69fb628664874.png"}

  = favicon_link_tag '/favicon.ico'
  = favicon_link_tag '/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'

  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => false
  %link{:href => "http://fonts.googleapis.com/css?family=Droid+Serif", :rel => "stylesheet", :type => "text/css"}
  %link{:href => "http://fonts.googleapis.com/css?family=Droid+Sans:400,700", :rel => "stylesheet", :type => "text/css"}
  = javascript_include_tag 'modernizr.custom.53769'

  %script{src: "//use.typekit.net/lqa5gqo.js", type: "text/javascript"}
  :javascript
    try{Typekit.load();}catch(e){}

  = csrf_meta_tag

app/views/layouts/_head.mobile.haml
%head
  %meta{:charset => "utf-8"}
  %link{:rel => "dns-prefetch", :href => "//ajax.googleapis.com"}

  %title= content_for?(:title) ? yield(:title) : "XXX"
  -# alternative title format.
  -# %title= content_for?(:title) ? ("XXX - " + yield(:title)) : "XXX"

  %meta{:name => "description", :content => "XXX"}
  %meta{:name => "HandheldFriendly", :content => "True"}
  %meta{:name => "MobileOptimized", :content => "320"}
  %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
  %meta{:name => "apple-mobile-web-app-capable", :content => "yes"}
  %meta{"http-equiv" => "cleartype", :content => "on"}

  %link{:rel => "apple-touch-icon-precomposed", :sizes => "144x144", :href => "/apple-touch-icon-144x144-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed", :sizes => "114x114", :href => "/apple-touch-icon-114x114-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed", :sizes => "72x72", :href => "/apple-touch-icon-72x72-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed", :href => "/apple-touch-icon-57x57-precomposed.png"}
  %link{:rel => "shortcut icon", :href => "/apple-touch-icon.png"}

  -# Tile icon for Win8 (144x144 + tile color)
  %meta{:name => "msapplication-TileImage", :content => "/apple-touch-icon-144x144-precomposed.png"}
  %meta{:name => "msapplication-TileColor", :content => "#222222"}

  -# For iOS web apps. Delete if not needed. https://github.com/h5bp/mobile-boilerplate/issues/94
  -# %meta{:name => "apple-mobile-web-app-capable", :content => "yes"}
  -# %meta{:name => "apple-mobile-web-app-status-bar-style", :content => "black"}
  -# %meta{:name => "apple-mobile-web-app-title", :content => ""}

  -# This script prevents links from opening in Mobile Safari. https://gist.github.com/1042026
  -# :javascript
  -#   (function(a,b,c){if(c in b&&b[c]){var d,e=a.location,f=/^(a|html)$/i;a.addEventListener("click",function(a){d=a.target;while(!f.test(d.nodeName))d=d.parentNode;"href"in d&&(d.href.indexOf("http")||~d.href.indexOf(e.host))&&(a.preventDefault(),e.href=d.href)},!1)}})(document,window.navigator,"standalone")

  = stylesheet_link_tag "mobile"
  -# for production customize modernizr at: http://www.modernizr.com/download/
  -# IMPORTANT: add the following to production.rb:
  -# config.assets.precompile += %w( modernizr-2.6.2.min.js )
  = javascript_include_tag 'modernizr-2.6.2.min'

  -# Google Web Fonts combination ideas. Delete what you do not use.
  %link{:href => "http://fonts.googleapis.com/css?family=Droid+Serif", :rel => "stylesheet", :type => "text/css"}
  %link{:href => "http://fonts.googleapis.com/css?family=Droid+Sans", :rel => "stylesheet", :type => "text/css"}

  -# %link{:href => "http://fonts.googleapis.com/css?family=Cantata+One", :rel => "stylesheet", :type => "text/css"}
  -# %link{:href => "http://fonts.googleapis.com/css?family=Imprima", :rel => "stylesheet", :type => "text/css"}

  -# %link{:href => "http://fonts.googleapis.com/css?family=Crimson+Text", :rel => "stylesheet", :type => "text/css"}
  -# %link{:href => "http://fonts.googleapis.com/css?family=Allerta", :rel => "stylesheet", :type => "text/css"}

  -# %link{:href => "http://fonts.googleapis.com/css?family=Arvo", :rel => "stylesheet", :type => "text/css"}
  -# %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans", :rel => "stylesheet", :type => "text/css"}

  -# %link{:href => "http://fonts.googleapis.com/css?family=PT+Serif:400,700", :rel => "stylesheet", :type => "text/css"}

  = csrf_meta_tag

  -# *******************************************************************************************
  -# MORE OPTIONS: (https://gist.github.com/849231)

  -# consider using below meta tags if you want to disable format detection by default
  -# %meta{:name => "format-detection", :content => "telephone=no"}
  -# %meta{:name => "format-detection", :content => "address=no"}

  -# consider using below link tag if the page is duplicate content of a desktop version
  -# %link{:rel => "canonical"}

app/views/layouts/_scripts.html.haml
= javascript_include_tag "application", "data-turbolinks-track" => true
= mobvious_javascript

:javascript
  (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
  function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
  e=o.createElement(i);r=o.getElementsByTagName(i)[0];
  e.src='//www.google-analytics.com/analytics.js';
  r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
  ga('create','UA-47555027-4');ga('send','pageview');

app/views/layouts/_scripts.mobile.haml
-# Uncomment if you plan to use google CDN and remove from manifest, otherwise delete.
-# %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"}
-# :javascript
-#   window.jQuery || document.write('<script src="assets/jquery-2.0.3.min.js"><\/script>')

= javascript_include_tag "mobile"

-# :javascript
-#   var _gaq=[["_setAccount","UA-XXXXX-X"],["_trackPageview"]];
-#   (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
-#   g.src='//www.google-analytics.com/ga.js';
-#   s.parentNode.insertBefore(g,s)}(document,"script"));

app/views/layouts/_utility.html.haml
.utility
  = render 'shared/social_media'
  -# %a{:href => golf_challenge_path, :title => 'Memoria Fund', :class => 'blue_btn'}
  -#   %span.hide-eq-4.hide-eq-6 Uuttukuu
  -#   %span.hide-eq-4 Snow Golf
  -#   Challenge
  %a{:href => education_path, :title => 'Scholarships', :class => 'cyan_btn'}
    Apply
    %span.hide-eq-4.hide-eq-6 for Scholarship
  %a{:href => support_path, :title => 'Become a sponsor', :class => 'blue_btn'} Suppport Us

app/views/layouts/application.html.haml
!!!
%html.no-js{:lang => "en"}
  = head

  %body{'data-authenticity_token' => form_authenticity_token}
    .wrapper
      = browsehappy
      %header{:role => "banner"}
        .container
          = link_to '', root_path, :title => 'Aqqaluk Trust', :class => 'logo'
          = yield :main_navigation
          = render :partial => 'layouts/utility'
      #main{:role => "main"}
        = yield
      = render :partial => 'layouts/footer'
    = scripts

app/views/layouts/application.mobile.haml
!!!
/[if IEMobile 7]><html class="no-js iem7"><![endif]
/[if (gt IEMobile 7)|!(IEMobile)]><!-->
%html.no-js
  /<![endif]

  = head
  %body
    %header{:role => "banner"}
      = render :partial => 'shared/logo'
      = render :partial => 'shared/navigation'
    #main{:role => "main"}
      = yield
    = render :partial => 'shared/footer'
    = scripts

app/views/mobile/layouts/_head.html.haml
%head
  %meta{:charset => "utf-8"}
  %link{:rel => "dns-prefetch", :href => "//use.typekit.net"}
  %link{:rel => "dns-prefetch", :href => "//ajax.googleapis.com"}

  %title= content_for?(:title) ? ("Aqqaluk Trust - " + yield(:title)) : "Aqqaluk Trust"

  %meta{:name => "description", :content => "Aqqaluk Trust"}
  %meta{:name => "HandheldFriendly", :content => "True"}
  %meta{:name => "MobileOptimized", :content => "320"}
  -# %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
  %meta{:name => "viewport", :content => "width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes"}
  %meta{:name => "apple-mobile-web-app-capable", :content => "yes"}
  %meta{"http-equiv" => "cleartype", :content => "on"}

  %link{:rel => "apple-touch-icon-precomposed", :sizes => "144x144", :href => "/touch/apple-touch-icon-144x144-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed", :sizes => "114x114", :href => "/touch/apple-touch-icon-114x114-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed", :sizes => "72x72",   :href => "/touch/apple-touch-icon-72x72-precomposed.png"}
  %link{:rel => "apple-touch-icon-precomposed",                      :href => "/touch/apple-touch-icon-57x57-precomposed.png"}
  %link{:rel => "shortcut icon",                :sizes => "196x196", :href => "/touch/touch-icon-196x196.png"}
  %link{:rel => "shortcut icon",                                     :href => "/touch/apple-touch-icon.png"}

  -# Tile icon for Win8 (144x144 + tile color)
  %meta{:name => "msapplication-TileImage", :content => "/apple-touch-icon-144x144-precomposed.png"}
  %meta{:name => "msapplication-TileColor", :content => "#222222"}

  = stylesheet_link_tag "mobile"
  %link{:href => "http://fonts.googleapis.com/css?family=Droid+Serif", :rel => "stylesheet", :type => "text/css"}
  %link{:href => "http://fonts.googleapis.com/css?family=Droid+Sans", :rel => "stylesheet", :type => "text/css"}
  = javascript_include_tag 'modernizr.custom.53769'

  %script{src: "//use.typekit.net/lqa5gqo.js", type: "text/javascript"}
  :javascript
    try{Typekit.load();}catch(e){}


  = csrf_meta_tag

app/views/mobile/layouts/_scripts.html.haml
= javascript_include_tag "mobile"
= mobvious_javascript

:javascript
  (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
  function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
  e=o.createElement(i);r=o.getElementsByTagName(i)[0];
  e.src='//www.google-analytics.com/analytics.js';
  r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
  ga('create','UA-47555027-4');ga('send','pageview');

app/views/mobile/layouts/application.html.haml
!!!
%html.no-js
  = head
  %body
    .wrapper
      %header{:role => "banner"}
        .container{:style => 'position: relative;'}
          = link_to '', root_path, :title => 'Aqqaluk Trust', :class => 'logo'
          = yield :mobile_navigation
      #main{:role => "main"}
        = yield
      = render :partial => 'layouts/footer'
    = scripts

app/views/nav/_main.html.haml
- content_for :main_navigation do
  %nav{role: 'navigation'}
    %a{:href => '#main', :title => '', :class => 'screen-reader-text'} Skip to main content
    .nav_primary
      -# %h3.screen-reader-text Sections:
      %ul.dropdown
        = nav_to 'Home', root_path, id: 'home'
        = nav_to 'About Us', about_us_path do
          %ul.sub-menu
            %li= link_to 'Founder', founder_path
            %li= link_to 'Board Members', board_members_path
            %li= link_to 'Staff', staff_path
            -# %li= link_to 'News & Events', news_path
            %li= link_to 'News & Events', '/news-and-events'
            %li= link_to 'Support Us', support_path
        = nav_to 'Education', education_path
        =# nav_to 'Savaktuq', savaktuq_path do
        = nav_to 'Savaktuq', '/savaktuq-resources' do
          %ul.sub-menu
            -# %li= link_to 'FAQ', faq_path
            %li= link_to 'FAQ', '/frequently-asked-questions'
            -# %li= link_to 'Student Blog', blog_path
            %li= link_to 'Student Blog', '/student-blog'
        = nav_to 'Language & Culture', language_path, id: 'language1'
        = nav_to 'Language', language_path, id: 'language2'
        = nav_to 'Camp', camp_path, class: 'nav-last'
        =# nav_to 'News & Events', news_path, id: 'news1'
        =# nav_to 'News', news_path, id: 'news2'
        =# nav_to 'Memorial Fund', memorial_fund_path

app/views/nav/_mobile.html.haml
- content_for :mobile_navigation do
  #header
    %a{:href => '#menu', :title => 'Menu'}

  %nav{:role => "navigation", :id => "menu"}
    %ul
      = nav_to 'Home', root_path
      = nav_to 'About Us', about_us_path
      = nav_to 'Founder', founder_path, class: 'mobile-sub'
      = nav_to 'Board Members', board_members_path, class: 'mobile-sub'
      = nav_to 'Staff', staff_path, class: 'mobile-sub'
      =# nav_to 'News & Events', news_path, class: 'mobile-sub'
      = nav_to 'News & Events', '/news-and-events', class: 'mobile-sub'
      = nav_to 'Support Us', support_path, class: 'mobile-sub'
      = nav_to 'Education', education_path
      =# nav_to 'Savaktuq', savaktuq_path
      = nav_to 'Savaktuq', '/savaktuq-resources'
      = nav_to 'FAQ', faq_path, class: 'mobile-sub'
      = nav_to 'Student Blog', blog_path, class: 'mobile-sub'
      = nav_to 'Language & Culture', language_path
      = nav_to 'Camp', camp_path

app/views/pages/_markdown_panel.html.haml
.markdown_panel{'data-edit_markdown_path' => edit_markdown_path, 'data-markdown_source_y' => markdown_source_z}
  = compile_markdown(markdown_source_z)

  = link_to 'edit', '#', class: 'markdown_panel_edit'

app/views/pages/_news_stories.html.haml
%h2 The 2014 Uuttukuu Snow Golf Challenge took place on February 28th.  Thank you all for supporting us throughout this year’s event!

= image_tag 'pics/news/NMs.jpg', :alt => ''

%p Interested in participating next year? Here's how to do it:

%ul
  %li Recruit a team of 4 of your most fun friends/colleagues
  %li Download the registration form
  %li Fill the registration form out completely and include payment
  %li Submit the registration form to the Aqqaluk Trust
  %li Come to the event location and don't forget your camera!

%a{:href => '#', :title => ''} CLICK HERE TO DOWNLOAD THE REGISTRATION FORM

%br

= image_tag 'pics/news/uuttukuu-logo.jpg', :alt => ''

app/views/pages/blog.html.haml
= title 'Student Blog'
= nav_switch 'Student Blog'

%section#blog.panel.hero
  .container
    %h1 Student Blogs
%section.panel.hero_bottom
  .container
    %p Need some kind of catchy enticement content for students to submit blogs here.

%section.panel#student-blog
  .container
    .student-blog
      %p Placeholder.

app/views/pages/founder.html.haml
= title 'Founder'
= nav_switch 'Founder'

%section#our-founder.panel.hero
  .container
    %h1 Founder
%section.panel.hero_bottom
  .container
    %p Add some content for this section.

%section.panel#newlin
  .container
    .newlin
      %p Roberty Aqqaluk Newlin - additional photos, quotes, and if possible soundbites

app/views/pages/language.html.haml
= title 'Language & Culture'
= nav_switch 'Language & Culture'

%section.panel#commission.hero
  .container
    %h1 Language &amp; Culture
%section.panel.hero_bottom
  .container
    %p In 2005 the Aqqaluk Trust and the Native Village of Kotzebue conducted a survey showing that only 14 percent of the regions residents understand Iñupiaq fluently, with 92% of fluent speakers over  the age of 65.
    #slidingDiv
      %p More Northwest Arctic Borough residents understand the Iñupiaq language, than speak it. For those residents over the age of 65, 96% indicated some degree of understanding the Iñupiaq language, while 70% of the residents under the age of 18 indicated an understanding.
      %p Eleven individual communities were surveyed. Seventy-two percent of the survey respondents did not indicate speaking ability, while 14% indicated the ability to speak the Iñupiaq language fluently.
    %a.show_hide{:href => "#", "data-link" => "#slidingDiv"} READ MORE

%section.panel#language_body
  .container
    .sidebar
      .box
        %h2#cd_rom.callout.callout_switch
          %span.hide-eq-4 The Iñupiaq Rosetta Stone CD-ROM
          %span.hide-gt-4 CD- ROM
          = link_to 'Order Now!', '/Inupiaq Language CD Order Form.pdf', :title => 'Order CD-ROM', :class => 'orange_btn'
    .image_row_1
      .image1
      .image2
    .language_top
      %p.callout The Coastal & Kobuk-Selawik dialect Iñupiaq Language CD-ROM learning tools are now available for purchase.
      %p.p_shrink The software program, developed by NANA with consultation from Rosetta-Stone, is instrumental in learning and  preserving the Iñupiaq Language in the Northwest Arctic and beyond.
      %p.p_shrink The Language CD-ROM is available for purchase for $195 each. Mail orders add $10.00 shipping and handling; additional orders ship for just $3 per CD-ROM.
      %p.p_shrink
        %a{href: 'http://www.rosettastone.com/system-requirements', title: ''} System Requirements
    .image_row_2
      .image3
      .image4
    .sidebar2
      %h2.callout
        %span.hide-eq-4 A little about the oral history project.
        %span.hide-gt-4 Oral History
    .sidebar3
      .box
        %h3.callout We envision that each generation can use the words of our elders to understand their story in today’s reality, and to carry on the values that ground us as Iñupiat.
    .language_bottom
      %p.p_shrink The Aqqaluk Trust has acquired nearly 750 audio cassette tapes of elders on a number of subjects, ranging from traditional subsistence practices to personal stories from the past. We know there may be other types of media content out there that need to be compiled, housed, and supported with the development of new multi-media.
      %p.p_shrink The Aqqaluk Trust strategies are to create a successful language revitalization effort. Teaching children through the creation of language nests is just one idea of how Iñupiaq can be more commonly spoken.
      %p.p_shrink The goal of the Aqqaluk Trust language department is to connect the Elders with the children through the creation of language nests. These language nests are events and places where Iñupiaq is exclusively spoken so that the children of the region are exposed to the language in practical settings.

app/views/pages/language_v1.html.haml
= title 'Language and Culture'
= nav_switch 'Language and Culture'

%section.panel#commission_v1
  .container
    %p In 2005 the Aqqaluk Trust and the Native Village of  Kotzebue conducted a survey showing that only 14 percent of the regions residents understand Iñupiaq fluently, with 92% of fluent speakers over  the age of 65.
    #slidingDiv_v1
      %p Realizing that the Iñupiaq language was in jeopardy, the Iñupiaq Language Commission was formed under the direction of the  Regional Elders Council to pursue ways to revitalize the language.
      %p The Iñupiaq Language Commission strategies are to create a successful language revitalization effort.
      %p Teaching children through the creation of language nests is just one idea of how Iñupiaq can be more commonly spoken. The goal of the Commission is to connect the Elders with the children through the creation of language nests. These language nests are events and places where Iñupiaq is exclusively spoken so that the children of the region are exposed to the language in practical settings.
    %a.show_hide{:href => "#", "data-link" => "#slidingDiv"} Read more

%section.panel#cd_v1
  .container
    .cd-image
      = link_to '', root_path, :title => 'Order Iñupiaq Language CD-ROM'
    %h2.purchase The Coastal & Kobuk-Selawik dialect Iñupiaq Language CD-ROM learning tools are now available for purchase.
    %p The software program, developed by NANA with consultation from Rosetta-Stone, is instrumental in learning and  preserving the Iñupiaq Language in the Northwest Arctic and beyond.
    %p The Language CD-ROM is available for purchase for $195 each. Mail orders add $10.00 shipping and handling; additional orders ship for just $3 per CD-ROM.

%section.panel#history_v1
  .container
    %h2 Oral History Project:
    .elder
    %p The Aqqaluk Trust has acquired nearly 750 audio cassette tapes of elders on a number of subjects, ranging from traditional subsistence practices to personal stories from the past.   We know there may be other types of media content out there that need to be compiled, housed, and supported with the development of new multi-media.  We envision that each generation can use the words of our elders to understand their story in today’s reality, and to carry on the values that ground us as Iñupiat.

app/views/pages/staff.html.haml
= title 'Staff'
= nav_switch 'Staff'

%section#our-staff.panel.hero
  .container
    %h1 Staff
%section.panel.hero_bottom
  .container
    %p Add some content for this section.

%section.panel#staff
  .container
    .staff
      %p Staff - photos and bios

app/views/shared/_footer.mobile.haml
%footer{:role => "contentinfo"}
  %ul
    %li
      = link_to 'About', root_path, :title => ''
    %li
      = link_to 'Site Map', root_path, :title => ''
    %li
      = link_to 'Terms of Use', root_path, :title => ''
    %li
      = link_to 'Privacy', root_path, :title => ''
    %li
      = link_to 'Contact', root_path, :title => ''
  %p.copyright &copy; XXX 2013